### ISSUE TITLE
T-shirt发车（4月29日截团）

### ISSUE THREAD

**Issue by myst729** [myst729/T#1]
> 认真生活，找点恶趣味。50件以上¥19.9一件，不到就¥32一件。
> https://www.tshe.com/items/151

## 暂定设计稿

背面脖子下面写啥字还没想好（Stay hungry, stay ... 😂）

![image](https://user-images.githubusercontent.com/519733/80007224-8d8ff880-84f8-11ea-96e4-ef07bb44e461.png)

## 素材

**https://www.iconfinder.com/icons/3561839/emoji_emoticon_silly_icon**

![image](https://user-images.githubusercontent.com/519733/80007495-e495cd80-84f8-11ea-982f-5ed60ba8bf5d.png)

## 颜色和款式

![image](https://user-images.githubusercontent.com/519733/80184875-f9c84480-863d-11ea-8294-1737f33d2637.png)

![image](https://user-images.githubusercontent.com/519733/80007647-20c92e00-84f9-11ea-85b0-a5d72700446a.png)

**Comment by galenyuan** [comment]
粽叔粉丝会专属T？

**Comment by myst729** [comment]
> 粽叔粉丝会专属T？

不是……来两件？

**Comment by galenyuan** [comment]
> > 粽叔粉丝会专属T？
> 
> 不是……来两件？

来一件 XL

**Comment by galenyuan** [comment]
> > 粽叔粉丝会专属T？
> 
> 不是……来两件？

一件男藏青色 XL
一件女白色 M

**Comment by chikara-chan** [comment]
黑底，黄色logo，这个配色是不是有点突兀....

**Comment by yusphy45** [comment]
@myst729 
一件男藏青2XL
一件女白S

**Comment by Jocs** [comment]
@myst729 
一件男藏青色 XL
一件女白色 M

**Comment by myst729** [comment]
> @myst729
> 一件男藏青2XL
> 一件女白S

ACK

**Comment by myst729** [comment]
> @myst729
> 一件男藏青色 XL
> 一件女白色 M

ACK

**Comment by myst729** [comment]
此条以上的参团信息全部ACK

**Comment by galenyuan** [comment]
1 件 XL / 藏青（男）
1 件 XXL  2 件 XL / 藏青（男）
2 件 L / 白色 （女）

**Comment by TooBug** [comment]
- 男2XL藏青
- 男2XL黑
- 男2XL麻灰
- 女XL白
- 女XL藏青

**Comment by myst729** [comment]
截团
